# Generated by Django 6.0.3 on 2026-04-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='es_vendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='esta_pausado',
            field=models.BooleanField(default=False),
        ),
    ]
