# Generated by Django 6.0.3 on 2026-04-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_product_es_vendido_product_esta_pausado'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categoria',
            field=models.CharField(choices=[('electronica', 'Electrónica'), ('computacion', 'Computación'), ('hogar', 'Hogar'), ('ropa', 'Ropa y Accesorios'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
    ]
